site_name: Atelier Mana Oasis
site_url: https://sitename.example
theme:
    name: material
    logo: assets/logo.png
    favicon: assets/favicon.ico
    font:
        text: Merriweather Sans
        code: Red Hat Mono
    palette:
        - scheme: slate
          toggle:
              icon: material/weather-sunny
              name: Dark mode
          primary: green
          accent: deep purple

        - scheme: default
          toggle:
              icon: material/weather-night
              name: Light mode
          primary: blue
          accent: deep orange
    features:
        - navigation.footer

extra:
  social:
    - icon: simple/youtube
      link: https://youtube.com
    - icon: simple/linkedin
      link: https://linkedin.com

copyright: Copyright &copy; 2024 neo-mashiro

markdown_extensions:
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg

    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets

    - pymdownx.tabbed:
        alternate_style: true

    - admonition
    - pymdownx.details

    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format


